<a href="https://colab.research.google.com/github/IntroComputationalPhysics-UNT/more-on-numpy-nworbehc/blob/main/More_on_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# More on NumPy

We have used NumPy already, but there is more that you can do with it, and much of its function is useful in physics modeling. NumPy provides fast, _vectorized_ numerical computations using arrays.

## Review

**Evaluate the following cells**

In [2]:
import numpy as np
np.__version__

'2.0.2'

In [3]:
# explore NumPy
dir(np)[:20] # first 20 entries

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__']

In [4]:
# get help for a specific function
help(np.sin)

Help on ufunc:

sin = <ufunc 'sin'>
    sin(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Trigonometric sine, element-wise.

    Parameters
    ----------
    x : array_like
        Angle, in radians (:math:`2 \pi` rad equals 360 degrees).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its original value.
        Note that if an uninitialized `out` array is created via the default
        ``

In [5]:
# COMPLETE THIS TASK
# Find documentation for np.linspace using '?'
np.linspace?

## Creating Vectors and Matrices

### Creating vectors

In [6]:
v1 = np.array([1, 2, 3])
v2 = np.linspace(0, 1, 5)
v3 = np.arange(0, 10, 2)
v1, v2, v3

(array([1, 2, 3]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]),
 array([0, 2, 4, 6, 8]))

### Creating matrices

In [7]:
A = np.array([[1, 2], [3, 4]])
Z = np.zeros((3,3))
I = np.eye(4)
A, Z, I

(array([[1, 2],
        [3, 4]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

### Indexing and slicing

In [20]:
A[0, 1], A[:, 0], A[1]

(np.int64(2), array([1, 3]), array([3, 4]))

### Random matrices

In [21]:
R = np.random.randn(3,3)
U = np.random.rand(3,3)
R, U

(array([[-0.48674307,  0.03987374,  0.15465048],
        [ 0.11093492, -0.53116008, -0.01502569],
        [-0.63880486,  1.20397475,  0.48233112]]),
 array([[0.7958156 , 0.43629912, 0.09290041],
        [0.56713221, 0.8752926 , 0.21642613],
        [0.68169786, 0.86186364, 0.13101823]]))

In [9]:
# COMPLETE THIS TASK
# Decompose a 5×5 random matrix into (real) symmetric and antisymmetric parts.
# A symmetric matrix A satisfies A = 0.5*(A + A.T);
# An antisymmetric matrix satisfies A = 0.5*(A - A.T);
# The `.T` attribute finds the transpose of the matrix.
RandomMatrix = np.random.randn(5,5)
A = 0.5*(RandomMatrix + RandomMatrix.T)
B = 0.5*(RandomMatrix - RandomMatrix.T)
A, B

(array([[-0.56662282,  0.10115313, -0.24612409, -0.29217789,  0.21001877],
        [ 0.10115313,  0.77804112,  0.41753627, -0.09657113, -0.7286703 ],
        [-0.24612409,  0.41753627,  0.42719344,  0.97645326,  0.33415797],
        [-0.29217789, -0.09657113,  0.97645326,  0.41236971,  0.25249369],
        [ 0.21001877, -0.7286703 ,  0.33415797,  0.25249369, -0.35552303]]),
 array([[ 0.        , -0.24631824,  0.41348313,  0.11410846,  0.36478633],
        [ 0.24631824,  0.        , -0.58518896,  0.77694486,  0.78705819],
        [-0.41348313,  0.58518896,  0.        , -0.39042214,  0.56859894],
        [-0.11410846, -0.77694486,  0.39042214,  0.        , -0.12011078],
        [-0.36478633, -0.78705819, -0.56859894,  0.12011078,  0.        ]]))

## Operations: *, @, and np.matmul / np.dot

Elementwise and matrix multiplication are treated differently in Numpy.

### Elementwise multiplication (`*`)

In [11]:
A = np.array([[1,2],[3,4]])
B = np.array([[10,20],[30,40]])
A * B

array([[ 10,  40],
       [ 90, 160]])

### Matrix multiplication (`@`)

In [12]:
A @ B

array([[ 70, 100],
       [150, 220]])

### Function equivalents for matrix multiplication

In [26]:
np.matmul(A, B), np.dot(A, B)

(array([[ 70, 100],
        [150, 220]]),
 array([[ 70, 100],
        [150, 220]]))

In [37]:
# COMPLETE THESE TASKS
# 1. look into the documentation for `np.matmul`, `np.dot`, `@`, and `*` and explain their difference(s)
#np.matmul: matmul is the matrix product of two arrays
#np.dot: dot is the dot product of 2 arrays
#@: @ is an operator that has the function of matrix multiplication
#*: * is an operator that has the function of elementwise multiplication
#source: https://peps.python.org/pep-0465/


# 2. create an example/examples to explain their differences
A = np.array([[1,0],
              [0,1]])
B = np.array([[1,2],
              [3,1]])
# * multiplies the corresponding values in the array,
# while @ performs actual matrix multiplication
#higher dimensional array examples
C = np.array([[[1,2],
               [3,4]],
              [[5,6],
               [7,8]]])
D = np.array([[[1,2],
               [3,4]],
              [[5,6],
               [7,8]]])
A @ B, A * B, np.matmul(C, D), np.dot(C, D)
#np.matmul acts like the @ operator, works for higher dimensional arrays
#np.dot is a general dot product

(array([[1, 2],
        [3, 1]]),
 array([[1, 0],
        [0, 1]]),
 array([[[  7,  10],
         [ 15,  22]],
 
        [[ 67,  78],
         [ 91, 106]]]),
 array([[[[  7,  10],
          [ 19,  22]],
 
         [[ 15,  22],
          [ 43,  50]]],
 
 
        [[[ 23,  34],
          [ 67,  78]],
 
         [[ 31,  46],
          [ 91, 106]]]]))

## Vectorization and Performance

_Vectorization_ means applying operations to whole arrays at once, rather than element by element.

### Loop version -- one element at a time

In [38]:
import math

In [41]:
%%timeit
xs = np.linspace(0, 10, 1_000_000) # here the '_' is used as a visual seperator -- i.e. 1,000,000
ys_loop = np.zeros_like(xs)
for i in range(len(xs)):
  ys_loop[i] = math.sin(xs[i])

251 ms ± 79.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### Vectorized version

In [43]:
%%timeit
xs = np.linspace(0, 10, 1_000_000)
y_vec = np.sin(xs)

16.6 ms ± 4.21 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
# COMPLETE THIS TASK
# ask Gemini about `%%timeit`
#Answer: %%timeit is a python feature that measures the execution time of python code.
# when placed at the beginning of a cell, it runs the code multiple times and
# provides statistical information about the execution speed.
# this is useful for comparing the performance of different code implementations

In [44]:
# COMPLETE THIS TASK
# create a vectorized function that calculates the total energy (T+U; kinetic + potential energy) of a harmonic oscillator
def totalenergy(k,x,m,v):
  """
  takes in spring constant k, position x, mass m, and velocity v
  returns the total energy of the harmonic oscillator
  """
  KEoscillator = 0.5*m*v**2
  PEoscillator = 0.5*k*x**2
  return KEoscillator + PEoscillator

## Eigenvalues and Eigenvectors

For a matrix $M$, eigenvalues $\lambda$ and eigenvectors $v$ satisfy:
$$ M v = \lambda v $$

In physics, these often realte to characteristic and measurable physical quantities:
* Oscillators → $\lambda$ relates to squared frequencies
* Quantum mechanics → $\lambda$ could be the energy eigenstates
* Rotations → $\lambda$ could define a principal axes

### Here is an example matrix

In [46]:
K = np.array([[ 1,-1, 0]
             ,[-1, 2,-1]
             ,[ 0,-1, 1] ])
vals, vecs = np.linalg.eigh(K)
vals, vecs

(array([9.99658224e-17, 1.00000000e+00, 3.00000000e+00]),
 array([[-5.77350269e-01, -7.07106781e-01,  4.08248290e-01],
        [-5.77350269e-01,  9.71445147e-17, -8.16496581e-01],
        [-5.77350269e-01,  7.07106781e-01,  4.08248290e-01]]))

In [ ]:
# COMPLETE THIS TASK
# In the above cell, which eigenvector is associated with which eigenvalue?
# The first eigenvalue is associated with the first eigenvector,
# the second eigenvalue is associated with the second eigenvector,
# and the third eigenvalue is associated with the third eigenvector.

## Quadratic Form: Diatomic Molecule Model

We can model a diatomic molecule (O$_2$ or N$_2$, for example) as two masses connected by a spring. Motion is restricted to the
bond axis.

The (quadratic) potential energy is: `V = 0.5 * x.T @ K @ x ` where `x = (x1, x2)`, the coordinates of the two atoms.

### Constructing a stiffness/force-constant matrix

In [47]:
k = 2450 # the force constant in an appropriate [energy]/[length] units
K = np.array([[ k,-k]
             ,[-k, k]])
K

array([[ 2450, -2450],
       [-2450,  2450]])

### Diagonalize to find frequencies and normal mode displacement patterns

In [48]:
vals, vecs = np.linalg.eigh(K)
vals, vecs

(array([   0., 4900.]),
 array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]))

### Vibrational frequencies (ignoring mass)

In [49]:
omega = np.sqrt(vals)
omega

array([ 0., 70.])

### Unitary transformations with eigenvector matrices

If the matrix is not singular, we can find eigenvalues and eigenvectors. The matrix of eigenvectors $U$ forms a unitary transformation.

In [53]:
# COMPLETE THESE TASKS
# Show that U@U.T and U.T@U are 2x2 identity matrices
# Note that normally we would need to use the `.conj().T` attribute to find the conjugate transpose matric, but our matrix is real.
U = np.array([[ 0.70710678, -0.70710678]
             ,[ 0.70710678,  0.70710678]])
U@U.T, U.T@U

#These values are super close to 1 and 0, which makes these matricies approximately equal to the identity matrix

(array([[ 9.99999997e-01, -1.18727821e-17],
        [-1.18727821e-17,  9.99999997e-01]]),
 array([[9.99999997e-01, 1.18727821e-17],
        [1.18727821e-17, 9.99999997e-01]]))

In [59]:
# COMPLETE THIS TASK
# From the eigenvalue equation M v = λ v, it follows that for U = [v1, v2], then M U = λ U.
# Because λ is diagonal and U.T@U = np.eye(2), it follows that λ = U.T @ K @ U.
# Confirm this behavior.

# First mode (translational mode)
# Eigenvector: both atoms move in the same direction, eigenvalue (frequency) is 0
mode1_displacement = vecs[:, 0] #
V1 = 0.5 * mode1_displacement.T @ K @ mode1_displacement
print(f"pe for mode 1 (translational): {V1:.2e}")

# Second mode (vibrational mode)
# Eigenvector: atoms move in opposite directions, eigenvalue (frequency) is non-zero
mode2_displacement = vecs[:, 1]
V2 = 0.5 * mode2_displacement.T @ K @ mode2_displacement
print(f"pe for mode 2 (vibrational): {V2:.2e}")

pe for mode 1 (translational): 0.00e+00
pe for mode 2 (vibrational): 2.45e+03
